# Generated by Django 4.2.7 on 2024-02-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jedinica_Mjere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_jedinice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tip_Proizvoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_tipa', models.CharField(max_length=100)),
                ('iznos_pdv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zaposlenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnicko_ime', models.CharField(max_length=200)),
                ('ime_zaposlenika', models.CharField(max_length=50)),
                ('prezime_zaposlenika', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_proizvoda', models.CharField(max_length=100)),
                ('opis_proizvoda', models.CharField(max_length=300)),
                ('jedinicna_cijena', models.FloatField()),
                ('kolicina', models.IntegerField()),
                ('jedinicna_osnovica_pdv', models.FloatField()),
                ('jedinicna_ukupna_cijena', models.FloatField()),
                ('jedinica_mjere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skladiste.jedinica_mjere')),
                ('tip_proizvoda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skladiste.tip_proizvoda')),
                ('zaposlenik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skladiste.zaposlenik')),
            ],
        ),
    ]
