# Generated by Django 4.2.7 on 2024-02-14 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skladiste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaposlenik',
            name='korisnicko_ime',
        ),
        migrations.AlterField(
            model_name='proizvod',
            name='zaposlenik',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
