# Generated by Django 4.2.7 on 2024-02-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skladiste', '0002_remove_zaposlenik_korisnicko_ime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaposlenik',
            name='korisnicko_ime',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
