# Generated by Django 4.2.7 on 2024-02-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skladiste', '0003_zaposlenik_korisnicko_ime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zaposlenik',
        ),
    ]
